version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webhook_db
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/webhook_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webhook_db
      ADMIN_API_KEY: ${ADMIN_API_KEY}

  worker:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/webhook_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: node dist/worker.js